# Generated by Django 4.0.5 on 2022-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formmchoices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formmmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newstypemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerquestionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteersmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
