# Generated by Django 4.0.5 on 2022-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0002_alter_faqsmodel_id_alter_formmchoices_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='headerbgimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Arxa fon şəkli'),
        ),
    ]
