# Generated by Django 4.0.5 on 2022-06-24 21:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0003_pagesettings_headerbgimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Başlıq şəkli')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mövzu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Tarix')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Vaxt')),
                ('address', models.CharField(max_length=256, verbose_name='Wnvan')),
            ],
            options={
                'verbose_name': 'Tədbir',
                'verbose_name_plural': 'Tədbirlər',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Footer loqo'),
        ),
    ]
