# Generated by Django 4.0.5 on 2022-06-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0004_eventmodel_pagesettings_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
