# Generated by Django 4.0.5 on 2022-06-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0005_socialmediaaccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='footer_map',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Xəritə'),
        ),
    ]
