# Generated by Django 4.0.5 on 2022-06-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0006_pagesettings_footer_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='footer_map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Xəritə linki'),
        ),
    ]
