# Generated by Django 4.0.5 on 2022-06-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0007_pagesettings_footer_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmchoices',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formchoices', to='gtib.formmmodel', verbose_name='Sorğu'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='categories',
            field=models.ManyToManyField(related_name='categorynews', to='gtib.newscategorymodel', verbose_name='Kateqoriyalar'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typenews', to='gtib.newstypemodel', verbose_name='Növ'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmediaaccounts', to='gtib.pagesettings', verbose_name='Parametrlər'),
        ),
    ]
