# Generated by Django 4.0.5 on 2022-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0008_alter_formmchoices_quiz_alter_newsmodel_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Ünvan'),
        ),
    ]
