# Generated by Django 4.0.5 on 2022-07-12 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0009_alter_eventmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('fathername', models.CharField(max_length=100, verbose_name='Ata adı')),
                ('position', models.CharField(blank=True, max_length=256, null=True, verbose_name='Vəzifə')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Haqqında')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Vəzifəyə başlama tarixi')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Loqo')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Keçid linki')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('fathername', models.CharField(max_length=100, verbose_name='Ata adı')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Haqqında')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Könüllü olma tarixi')),
                ('events', models.TextField(blank=True, null=True, verbose_name='İştirak etdiyi tədbirlər')),
            ],
            options={
                'verbose_name': 'Könüllü',
                'verbose_name_plural': 'Könüllü',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='volunteersmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Könüllü müraciəti', 'verbose_name_plural': 'Könüllü müraciətləri'},
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='about',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about1',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqımızda 1-ci hissə'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about2',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqımızda 2-ci hissə'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about3',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqımızda 3-cü hissə'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about4',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqımızda 4-cü hissə'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about_img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil 1'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='about_img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil 2'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='charter_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AddField(
            model_name='volunteersmodel',
            name='apply_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Müraciət tarixi'),
        ),
        migrations.AlterField(
            model_name='volunteersmodel',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
    ]
