# Generated by Django 4.0.5 on 2022-07-12 14:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0010_directormodel_partnermodel_volunteermodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directormodel',
            options={'ordering': ('-id',), 'verbose_name': 'İdarə heyəti üzvü', 'verbose_name_plural': 'İdarə heyəti'},
        ),
        migrations.AlterModelOptions(
            name='partnermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Tərəfdaş', 'verbose_name_plural': 'Tərəfdaşlar'},
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='charter',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nizamnamə'),
        ),
    ]
