# Generated by Django 4.0.5 on 2022-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0012_directormodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
