# Generated by Django 4.0.5 on 2022-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0013_volunteermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthOrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Loqo')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Keçid linki')),
            ],
            options={
                'verbose_name': 'Gənclər Təşkilatı',
                'verbose_name_plural': 'Gənclər Təşkilatları',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='volunteermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Könüllü', 'verbose_name_plural': 'Könüllülər'},
        ),
    ]
