# Generated by Django 4.0.5 on 2022-07-22 16:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0015_ebookmodel_newsmodel_slug_pagesettings_culture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='karabakh',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Qarabağ Azərbaycandır!'),
        ),
    ]
