# Generated by Django 4.0.5 on 2022-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0016_alter_pagesettings_karabakh'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Haqqında')),
                ('slug', models.SlugField(max_length=256, verbose_name='Sluq')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Nəşr tarixi')),
            ],
            options={
                'verbose_name': 'Nəşr',
                'verbose_name_plural': 'Nəşrlər',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='ebookmodel',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Kitab'),
        ),
    ]
