# Generated by Django 4.0.5 on 2022-07-23 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0017_printmodel_ebookmodel_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteersmodel',
            name='address',
        ),
        migrations.AlterField(
            model_name='printmodel',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi'),
        ),
    ]
