# Generated by Django 4.0.5 on 2022-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0019_offermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Fayl')),
                ('idea', models.TextField(verbose_name='İdeaya haqqında')),
                ('sent_date', models.DateTimeField(verbose_name='Göndərildi')),
            ],
            options={
                'verbose_name': 'İdeya',
                'verbose_name_plural': 'İdeyalar',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Təklif', 'verbose_name_plural': 'Təkliflər'},
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='idea',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='message',
            field=models.TextField(default='', verbose_name='Mesaj'),
            preserve_default=False,
        ),
    ]
