# Generated by Django 4.0.5 on 2022-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0020_ideamodel_alter_offermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('pub_date', models.DateField(verbose_name='Tarix')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotolar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('pub_date', models.DateField(verbose_name='Tarix')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotolar',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='ideamodel',
            name='idea',
            field=models.TextField(verbose_name='İdeya haqqında'),
        ),
    ]
