# Generated by Django 4.0.5 on 2022-07-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0022_newsmodel_meta_description_newsmodel_meta_keyword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintModel',
        ),
        migrations.DeleteModel(
            name='YouthOrganizationModel',
        ),
    ]
