# Generated by Django 3.1.5 on 2022-08-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtib', '0024_auto_20220823_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotolar'},
        ),
        migrations.AddField(
            model_name='photomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='ebookmodel',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='photosmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtib.photomodel', verbose_name='Qalereya'),
        ),
    ]
